amanda_chau/week5/tuesday-aussie-animals-db/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

# planets CRUD system

# Create routes

get "/aussie_animals/new" => "animals#new", as: 'animals_new'

post "/aussie_animals" => "animals#create"



# Read routes
get "/aussie_animals" => "animals#index", as: 'animals'

get "/aussie_animals/:id" => "animals#show", as: 'animal'



# Update routes

get "/aussie_animals/:id/edit" =>  "animals#edit", as: 'animals_edit'

post "/aussie_animals/:id" => "animals#update"


# Delete routes

get "/aussie_animals/:id/delete" => "animals#delete", as: 'animals_delete'


end

amanda_chau/week5/tuesday-aussie-animals-db/app/models/animal.rb
class Animal < ApplicationRecord

    # this enables us to write to access the table animals by writing code like Animal.all
    # File and class must be singular
end

amanda_chau/week5/tuesday-aussie-animals-db/app/controllers/animals_controller.rb
class AnimalsController < ApplicationController

skip_before_action :verify_authenticity_token, raise: false
#create
  def new

  end

  def create

    Animal.create(
      name: params[:name],
      image: params[:image],
      location: params[:location],
      diet: params[:diet],
      min_mass: params[:min_mass],
      max_mass: params[:max_mass],
      lifespan: params[:lifespan],
      marsupial: params[:marsupial]
    )

  redirect_to(animals_path)
  end



#Read

  def index
    @animals = Animal.all
  end

  def show
    @animal = Animal.find params[:id]
  end

#update
  def edit
    @animal = Animal.find params[:id]
  end

  def update
    animal = Animal.find params[:id]
    animal.update(
      name: params[:name],
      image: params[:image],
      location: params[:location],
      diet: params[:diet],
      min_mass: params[:min_mass],
      max_mass: params[:max_mass],
      lifespan: params[:lifespan],
      marsupial: params[:marsupial]
    )
    redirect_to( animal_path(animal.id) )
  end

#Delete
  def delete
    Animal.destroy params[:id]

    redirect_to( animals_path )

  end

end

amanda_chau/week5/tuesday-aussie-animals-db/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TuesdayAussieAnimalsDb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>
   <h1>Learn About Aussie Animals </h1>
   <nav>
     <a href="<%= animals_path %>">Index</a>
     |
     <a href="<%= animals_new_path %>">Add new animal</a>
   </nav>

   <hr>
    <body>
      <%= yield %>
    </body>
    <hr>
    <footer>
      &copy; 2019 No More Zoos Co.
    </footer>
</html>