david_wade/week5/tuesday/islands-db/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

#Read Routes
get '/islands' => 'islands#index'
get '/islands/:id' => 'islands#show', as: 'island'

#Update Routes
get '/islands/:id/edit' => 'islands#edit', as: 'island_edit'
post '/islands/:id' => 'islands#update'



end

david_wade/week5/tuesday/islands-db/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

david_wade/week5/tuesday/islands-db/app/models/island.rb
class Island < ApplicationRecord

end

david_wade/week5/tuesday/islands-db/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

david_wade/week5/tuesday/islands-db/app/controllers/islands_controller.rb
class IslandsController < ApplicationController

  skip_before_action :verify_authenticity_token, raise: false







  #READ - indexpage
  def index
    @islands = Island.all
  end

def show
  @island = Island.find params[:id]
end

#Update - edit/update
def edit
  @island = Island.find params[:id]
end

def update
  island = Island.find params[:id]
  island.update(
    name: params[:name],
    demonym: params[:demonym],
    capital: params[:capital],
    currency: params[:currency],
    area: params[:area],
    image: params[:image]
  )

  redirect_to ( island_path(island.id) )
end






















end

david_wade/week5/tuesday/islands-db/app/helpers/application_helper.rb
module ApplicationHelper
end

david_wade/week5/tuesday/islands-db/app/views/islands/edit.html.erb
<h2>Edit: <%= @island.name %></h2>

<form action="<%= island_path(@island.id) %>" method="post">

  <label>
    Name: <input type="text" name="name" value="<%= @island.name %>">
  </label>
  <br>
  <label>
    Demonym: <input type="text" name="demonym" value="<%= @island.demonym %>">
  </label>
  <br>
  <label>
    Capital: <input type="text" name="capital" value="<%= @island.capital %>">
  </label>
  <br>
  <label>
    Currency: <input type="text" name="currency" value="<%= @island.currency %>">
  </label>
  <br>
  <label>
    Area: <input type="text" name="area" value="<%= @island.area %>">
  </label>
  <br>
  <label>
    Image: <input type="text" name="image" value="<%= @island.image %>">
  </label>
  <br>
  <input type="submit" name="" value="update">


</form>

david_wade/week5/tuesday/islands-db/app/views/islands/index.html.erb
<h2>Index</h2>

<ul>
  <% @islands.each do |islands| %>
  <li>
    <a href="<%= island_path(islands.id) %>"><%= islands.name %></a>
  </li>
  <% end %>
</ul>

david_wade/week5/tuesday/islands-db/app/views/islands/show.html.erb
<h2><%= @island.name %></h2>

<a href="<%= island_edit_path(@island.id) %>">Edit</a>


<p>
  <strong>Name:</strong>
  <%= @island.name %>
</p>
<p>
  <strong>Demonym:</strong>
  <%= @island.demonym %>
</p>
<p>
  <strong>Capital:</strong>
  <%= @island.capital %>
</p>
<p>
  <strong>Currency:</strong>
  <%= @island.currency %>
</p>
<p>
  <strong>Area:</strong>
  <%= @island.area %>
  Square Kilometres
</p>


<% if @island.image.present? %>
<%=  image_tag @island.image, alt: @island.name, class: 'island-show'%>
<% end %>

david_wade/week5/tuesday/islands-db/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IslandsDb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <h1>Islands</h1>
    <hr>
    <%= yield %>
    <hr>
  </body>
</html>